/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'id' : bigint,
  'labelText' : [] | [string],
  'topCategories' : Array<TalentCategory>,
  'timestamp' : bigint,
  'talentScores' : Array<TalentScore>,
  'profile' : SocialProfile,
}
export type ContentType = { 'video' : null } |
  { 'text' : null } |
  { 'links' : null } |
  { 'images' : null };
export type EngagementStyle = { 'creator' : null } |
  { 'commenter' : null } |
  { 'sharer' : null } |
  { 'lurker' : null };
export type PostingFrequency = { 'monthly' : null } |
  { 'rarely' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type SocialPlatform = { 'linkedin' : null } |
  { 'tiktok' : null } |
  { 'twitter' : null } |
  { 'instagram' : null } |
  { 'facebook' : null } |
  { 'youtube' : null } |
  { 'reddit' : null };
export interface SocialProfile {
  'contentTypes' : Array<ContentType>,
  'interests' : Array<string>,
  'name' : string,
  'platform' : SocialPlatform,
  'topics' : Array<string>,
  'engagementStyle' : EngagementStyle,
  'postingFrequency' : PostingFrequency,
}
export type TalentCategory = { 'communication' : null } |
  { 'strategic' : null } |
  { 'analytical' : null } |
  { 'creative' : null } |
  { 'technical' : null } |
  { 'leadership' : null } |
  { 'entrepreneurial' : null } |
  { 'empathetic' : null };
export interface TalentScore {
  'score' : bigint,
  'insight' : string,
  'category' : TalentCategory,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSeeds' : ActorMethod<[], undefined>,
  'deleteAnalysis' : ActorMethod<[bigint], undefined>,
  'getAnalysis' : ActorMethod<[bigint], AnalysisResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTalentCategoryOrder' : ActorMethod<[TalentCategory], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAnalyses' : ActorMethod<[], Array<AnalysisResult>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAnalysis' : ActorMethod<
    [SocialProfile, [] | [string]],
    AnalysisResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];