/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TalentCategory = IDL.Variant({
  'communication' : IDL.Null,
  'strategic' : IDL.Null,
  'analytical' : IDL.Null,
  'creative' : IDL.Null,
  'technical' : IDL.Null,
  'leadership' : IDL.Null,
  'entrepreneurial' : IDL.Null,
  'empathetic' : IDL.Null,
});
export const TalentScore = IDL.Record({
  'score' : IDL.Nat,
  'insight' : IDL.Text,
  'category' : TalentCategory,
});
export const ContentType = IDL.Variant({
  'video' : IDL.Null,
  'text' : IDL.Null,
  'links' : IDL.Null,
  'images' : IDL.Null,
});
export const SocialPlatform = IDL.Variant({
  'linkedin' : IDL.Null,
  'tiktok' : IDL.Null,
  'twitter' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
  'youtube' : IDL.Null,
  'reddit' : IDL.Null,
});
export const EngagementStyle = IDL.Variant({
  'creator' : IDL.Null,
  'commenter' : IDL.Null,
  'sharer' : IDL.Null,
  'lurker' : IDL.Null,
});
export const PostingFrequency = IDL.Variant({
  'monthly' : IDL.Null,
  'rarely' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const SocialProfile = IDL.Record({
  'contentTypes' : IDL.Vec(ContentType),
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'platform' : SocialPlatform,
  'topics' : IDL.Vec(IDL.Text),
  'engagementStyle' : EngagementStyle,
  'postingFrequency' : PostingFrequency,
});
export const AnalysisResult = IDL.Record({
  'id' : IDL.Nat,
  'labelText' : IDL.Opt(IDL.Text),
  'topCategories' : IDL.Vec(TalentCategory),
  'timestamp' : IDL.Int,
  'talentScores' : IDL.Vec(TalentScore),
  'profile' : SocialProfile,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSeeds' : IDL.Func([], [], []),
  'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
  'getAnalysis' : IDL.Func([IDL.Nat], [AnalysisResult], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTalentCategoryOrder' : IDL.Func([TalentCategory], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAnalysis' : IDL.Func(
      [SocialProfile, IDL.Opt(IDL.Text)],
      [AnalysisResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TalentCategory = IDL.Variant({
    'communication' : IDL.Null,
    'strategic' : IDL.Null,
    'analytical' : IDL.Null,
    'creative' : IDL.Null,
    'technical' : IDL.Null,
    'leadership' : IDL.Null,
    'entrepreneurial' : IDL.Null,
    'empathetic' : IDL.Null,
  });
  const TalentScore = IDL.Record({
    'score' : IDL.Nat,
    'insight' : IDL.Text,
    'category' : TalentCategory,
  });
  const ContentType = IDL.Variant({
    'video' : IDL.Null,
    'text' : IDL.Null,
    'links' : IDL.Null,
    'images' : IDL.Null,
  });
  const SocialPlatform = IDL.Variant({
    'linkedin' : IDL.Null,
    'tiktok' : IDL.Null,
    'twitter' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
    'youtube' : IDL.Null,
    'reddit' : IDL.Null,
  });
  const EngagementStyle = IDL.Variant({
    'creator' : IDL.Null,
    'commenter' : IDL.Null,
    'sharer' : IDL.Null,
    'lurker' : IDL.Null,
  });
  const PostingFrequency = IDL.Variant({
    'monthly' : IDL.Null,
    'rarely' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const SocialProfile = IDL.Record({
    'contentTypes' : IDL.Vec(ContentType),
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'platform' : SocialPlatform,
    'topics' : IDL.Vec(IDL.Text),
    'engagementStyle' : EngagementStyle,
    'postingFrequency' : PostingFrequency,
  });
  const AnalysisResult = IDL.Record({
    'id' : IDL.Nat,
    'labelText' : IDL.Opt(IDL.Text),
    'topCategories' : IDL.Vec(TalentCategory),
    'timestamp' : IDL.Int,
    'talentScores' : IDL.Vec(TalentScore),
    'profile' : SocialProfile,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSeeds' : IDL.Func([], [], []),
    'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
    'getAnalysis' : IDL.Func([IDL.Nat], [AnalysisResult], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTalentCategoryOrder' : IDL.Func([TalentCategory], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAnalysis' : IDL.Func(
        [SocialProfile, IDL.Opt(IDL.Text)],
        [AnalysisResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };