/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TalentScore {
    score: bigint;
    insight: string;
    category: TalentCategory;
}
export interface SocialProfile {
    contentTypes: Array<ContentType>;
    interests: Array<string>;
    name: string;
    platform: SocialPlatform;
    topics: Array<string>;
    engagementStyle: EngagementStyle;
    postingFrequency: PostingFrequency;
}
export interface UserProfile {
    name: string;
}
export interface AnalysisResult {
    id: bigint;
    labelText?: string;
    topCategories: Array<TalentCategory>;
    timestamp: bigint;
    talentScores: Array<TalentScore>;
    profile: SocialProfile;
}
export enum ContentType {
    video = "video",
    text = "text",
    links = "links",
    images = "images"
}
export enum EngagementStyle {
    creator = "creator",
    commenter = "commenter",
    sharer = "sharer",
    lurker = "lurker"
}
export enum PostingFrequency {
    monthly = "monthly",
    rarely = "rarely",
    daily = "daily",
    weekly = "weekly"
}
export enum SocialPlatform {
    linkedin = "linkedin",
    tiktok = "tiktok",
    twitter = "twitter",
    instagram = "instagram",
    facebook = "facebook",
    youtube = "youtube",
    reddit = "reddit"
}
export enum TalentCategory {
    communication = "communication",
    strategic = "strategic",
    analytical = "analytical",
    creative = "creative",
    technical = "technical",
    leadership = "leadership",
    entrepreneurial = "entrepreneurial",
    empathetic = "empathetic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createSeeds(): Promise<void>;
    deleteAnalysis(id: bigint): Promise<void>;
    getAnalysis(id: bigint): Promise<AnalysisResult>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTalentCategoryOrder(category: TalentCategory): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAnalyses(): Promise<Array<AnalysisResult>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAnalysis(profile: SocialProfile, labelText: string | null): Promise<AnalysisResult>;
}
import type { AnalysisResult as _AnalysisResult, ContentType as _ContentType, EngagementStyle as _EngagementStyle, PostingFrequency as _PostingFrequency, SocialPlatform as _SocialPlatform, SocialProfile as _SocialProfile, TalentCategory as _TalentCategory, TalentScore as _TalentScore, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSeeds(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSeeds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSeeds();
            return result;
        }
    }
    async deleteAnalysis(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return result;
        }
    }
    async getAnalysis(arg0: bigint): Promise<AnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_AnalysisResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_AnalysisResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTalentCategoryOrder(arg0: TalentCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTalentCategoryOrder(to_candid_TalentCategory_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTalentCategoryOrder(to_candid_TalentCategory_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAnalyses(): Promise<Array<AnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalyses();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalyses();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitAnalysis(arg0: SocialProfile, arg1: string | null): Promise<AnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnalysis(to_candid_SocialProfile_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AnalysisResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnalysis(to_candid_SocialProfile_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AnalysisResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalysisResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): AnalysisResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_EngagementStyle_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EngagementStyle): EngagementStyle {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PostingFrequency_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostingFrequency): PostingFrequency {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SocialPlatform_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialPlatform): SocialPlatform {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SocialProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialProfile): SocialProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TalentCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TalentCategory): TalentCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TalentScore_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TalentScore): TalentScore {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    score: bigint;
    insight: string;
    category: _TalentCategory;
}): {
    score: bigint;
    insight: string;
    category: TalentCategory;
} {
    return {
        score: value.score,
        insight: value.insight,
        category: from_candid_TalentCategory_n7(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentTypes: Array<_ContentType>;
    interests: Array<string>;
    name: string;
    platform: _SocialPlatform;
    topics: Array<string>;
    engagementStyle: _EngagementStyle;
    postingFrequency: _PostingFrequency;
}): {
    contentTypes: Array<ContentType>;
    interests: Array<string>;
    name: string;
    platform: SocialPlatform;
    topics: Array<string>;
    engagementStyle: EngagementStyle;
    postingFrequency: PostingFrequency;
} {
    return {
        contentTypes: from_candid_vec_n14(_uploadFile, _downloadFile, value.contentTypes),
        interests: value.interests,
        name: value.name,
        platform: from_candid_SocialPlatform_n17(_uploadFile, _downloadFile, value.platform),
        topics: value.topics,
        engagementStyle: from_candid_EngagementStyle_n19(_uploadFile, _downloadFile, value.engagementStyle),
        postingFrequency: from_candid_PostingFrequency_n21(_uploadFile, _downloadFile, value.postingFrequency)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    labelText: [] | [string];
    topCategories: Array<_TalentCategory>;
    timestamp: bigint;
    talentScores: Array<_TalentScore>;
    profile: _SocialProfile;
}): {
    id: bigint;
    labelText?: string;
    topCategories: Array<TalentCategory>;
    timestamp: bigint;
    talentScores: Array<TalentScore>;
    profile: SocialProfile;
} {
    return {
        id: value.id,
        labelText: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.labelText)),
        topCategories: from_candid_vec_n6(_uploadFile, _downloadFile, value.topCategories),
        timestamp: value.timestamp,
        talentScores: from_candid_vec_n9(_uploadFile, _downloadFile, value.talentScores),
        profile: from_candid_SocialProfile_n12(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    text: null;
} | {
    links: null;
} | {
    images: null;
}): ContentType {
    return "video" in value ? ContentType.video : "text" in value ? ContentType.text : "links" in value ? ContentType.links : "images" in value ? ContentType.images : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin: null;
} | {
    tiktok: null;
} | {
    twitter: null;
} | {
    instagram: null;
} | {
    facebook: null;
} | {
    youtube: null;
} | {
    reddit: null;
}): SocialPlatform {
    return "linkedin" in value ? SocialPlatform.linkedin : "tiktok" in value ? SocialPlatform.tiktok : "twitter" in value ? SocialPlatform.twitter : "instagram" in value ? SocialPlatform.instagram : "facebook" in value ? SocialPlatform.facebook : "youtube" in value ? SocialPlatform.youtube : "reddit" in value ? SocialPlatform.reddit : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: null;
} | {
    commenter: null;
} | {
    sharer: null;
} | {
    lurker: null;
}): EngagementStyle {
    return "creator" in value ? EngagementStyle.creator : "commenter" in value ? EngagementStyle.commenter : "sharer" in value ? EngagementStyle.sharer : "lurker" in value ? EngagementStyle.lurker : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    rarely: null;
} | {
    daily: null;
} | {
    weekly: null;
}): PostingFrequency {
    return "monthly" in value ? PostingFrequency.monthly : "rarely" in value ? PostingFrequency.rarely : "daily" in value ? PostingFrequency.daily : "weekly" in value ? PostingFrequency.weekly : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    communication: null;
} | {
    strategic: null;
} | {
    analytical: null;
} | {
    creative: null;
} | {
    technical: null;
} | {
    leadership: null;
} | {
    entrepreneurial: null;
} | {
    empathetic: null;
}): TalentCategory {
    return "communication" in value ? TalentCategory.communication : "strategic" in value ? TalentCategory.strategic : "analytical" in value ? TalentCategory.analytical : "creative" in value ? TalentCategory.creative : "technical" in value ? TalentCategory.technical : "leadership" in value ? TalentCategory.leadership : "entrepreneurial" in value ? TalentCategory.entrepreneurial : "empathetic" in value ? TalentCategory.empathetic : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentType>): Array<ContentType> {
    return value.map((x)=>from_candid_ContentType_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisResult>): Array<AnalysisResult> {
    return value.map((x)=>from_candid_AnalysisResult_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TalentCategory>): Array<TalentCategory> {
    return value.map((x)=>from_candid_TalentCategory_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TalentScore>): Array<TalentScore> {
    return value.map((x)=>from_candid_TalentScore_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ContentType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_EngagementStyle_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngagementStyle): _EngagementStyle {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_PostingFrequency_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostingFrequency): _PostingFrequency {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_SocialPlatform_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialPlatform): _SocialPlatform {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_SocialProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialProfile): _SocialProfile {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_TalentCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TalentCategory): _TalentCategory {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentTypes: Array<ContentType>;
    interests: Array<string>;
    name: string;
    platform: SocialPlatform;
    topics: Array<string>;
    engagementStyle: EngagementStyle;
    postingFrequency: PostingFrequency;
}): {
    contentTypes: Array<_ContentType>;
    interests: Array<string>;
    name: string;
    platform: _SocialPlatform;
    topics: Array<string>;
    engagementStyle: _EngagementStyle;
    postingFrequency: _PostingFrequency;
} {
    return {
        contentTypes: to_candid_vec_n31(_uploadFile, _downloadFile, value.contentTypes),
        interests: value.interests,
        name: value.name,
        platform: to_candid_SocialPlatform_n34(_uploadFile, _downloadFile, value.platform),
        topics: value.topics,
        engagementStyle: to_candid_EngagementStyle_n36(_uploadFile, _downloadFile, value.engagementStyle),
        postingFrequency: to_candid_PostingFrequency_n38(_uploadFile, _downloadFile, value.postingFrequency)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TalentCategory): {
    communication: null;
} | {
    strategic: null;
} | {
    analytical: null;
} | {
    creative: null;
} | {
    technical: null;
} | {
    leadership: null;
} | {
    entrepreneurial: null;
} | {
    empathetic: null;
} {
    return value == TalentCategory.communication ? {
        communication: null
    } : value == TalentCategory.strategic ? {
        strategic: null
    } : value == TalentCategory.analytical ? {
        analytical: null
    } : value == TalentCategory.creative ? {
        creative: null
    } : value == TalentCategory.technical ? {
        technical: null
    } : value == TalentCategory.leadership ? {
        leadership: null
    } : value == TalentCategory.entrepreneurial ? {
        entrepreneurial: null
    } : value == TalentCategory.empathetic ? {
        empathetic: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    video: null;
} | {
    text: null;
} | {
    links: null;
} | {
    images: null;
} {
    return value == ContentType.video ? {
        video: null
    } : value == ContentType.text ? {
        text: null
    } : value == ContentType.links ? {
        links: null
    } : value == ContentType.images ? {
        images: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialPlatform): {
    linkedin: null;
} | {
    tiktok: null;
} | {
    twitter: null;
} | {
    instagram: null;
} | {
    facebook: null;
} | {
    youtube: null;
} | {
    reddit: null;
} {
    return value == SocialPlatform.linkedin ? {
        linkedin: null
    } : value == SocialPlatform.tiktok ? {
        tiktok: null
    } : value == SocialPlatform.twitter ? {
        twitter: null
    } : value == SocialPlatform.instagram ? {
        instagram: null
    } : value == SocialPlatform.facebook ? {
        facebook: null
    } : value == SocialPlatform.youtube ? {
        youtube: null
    } : value == SocialPlatform.reddit ? {
        reddit: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngagementStyle): {
    creator: null;
} | {
    commenter: null;
} | {
    sharer: null;
} | {
    lurker: null;
} {
    return value == EngagementStyle.creator ? {
        creator: null
    } : value == EngagementStyle.commenter ? {
        commenter: null
    } : value == EngagementStyle.sharer ? {
        sharer: null
    } : value == EngagementStyle.lurker ? {
        lurker: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostingFrequency): {
    monthly: null;
} | {
    rarely: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == PostingFrequency.monthly ? {
        monthly: null
    } : value == PostingFrequency.rarely ? {
        rarely: null
    } : value == PostingFrequency.daily ? {
        daily: null
    } : value == PostingFrequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ContentType>): Array<_ContentType> {
    return value.map((x)=>to_candid_ContentType_n32(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
